In [16]:
import pandas as pd
from pathlib import Path
import re
import time
import gc
import shutil

# ==================================================
# SETTINGS
# ==================================================

folder = Path("degree_year")

output_file = Path("IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv")

CHUNK_SIZE = 100_000

# ==================================================
# DELETE OLD OUTPUT FIRST
# Prevents old bad rows / NaN rows from staying
# ==================================================

if output_file.exists():
    output_file.unlink()
    print(f"Deleted old output file: {output_file}")

# ==================================================
# AWARD LEVEL MAP
# ==================================================

award_level_map = {
    1: "Certificate < 1 year",
    2: "Certificate 1-2 years",
    3: "Associate",
    4: "Certificate 2-4 years",
    5: "Bachelor",
    6: "Post-baccalaureate certificate",
    7: "Master",
    8: "Post-master certificate",
    9: "Doctor",
    10: "First-professional degree",
    11: "First-professional certificate",
    17: "Doctor - research/scholarship",
    18: "Doctor - professional practice",
    19: "Doctor - other",
}

def degree_group(x):
    if pd.isna(x):
        return "Unknown"

    try:
        x = int(x)
    except:
        return "Unknown"

    if x == 3:
        return "Associate"
    elif x == 5:
        return "Bachelor"
    elif x == 7:
        return "Master"
    elif x in [9, 17, 18, 19]:
        return "Doctor"
    elif x in [1, 2, 4, 6, 8, 10, 11]:
        return "Certificate/Other"
    else:
        return "Unknown"

# ==================================================
# HELPER FUNCTIONS
# ==================================================

def clean_text(value):
    """
    Cleans text and prevents NaN.
    """
    if pd.isna(value):
        return "Unknown"

    value = str(value).strip()

    if value.lower() in ["nan", "none", "null", ""]:
        return "Unknown"

    value = re.sub(r"\s+", " ", value).strip()

    if value == "":
        return "Unknown"

    return value


def find_column(df, possible_names):
    """
    Finds a column even if column names have different uppercase/lowercase.
    """
    col_map = {col.upper().strip(): col for col in df.columns}

    for name in possible_names:
        if name.upper().strip() in col_map:
            return col_map[name.upper().strip()]

    return None


def get_year_from_filename(filename):
    match = re.search(r"(19|20)\d{2}", filename)
    if match:
        return int(match.group())
    return pd.NA


def format_seconds(seconds):
    seconds = int(seconds)

    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60

    if h > 0:
        return f"{h}h {m}m {s}s"
    elif m > 0:
        return f"{m}m {s}s"
    else:
        return f"{s}s"


def make_major_name(chunk, major_col, cip_col):
    """
    If major title exists, use it.
    If not, use CIP code.
    This prevents clean_major_name from becoming NaN.
    """
    if major_col:
        major = chunk[major_col].apply(clean_text)
    else:
        major = pd.Series(["Unknown"] * len(chunk), index=chunk.index)

    if cip_col:
        cip_clean = chunk[cip_col].apply(clean_text)
    else:
        cip_clean = pd.Series(["Unknown"] * len(chunk), index=chunk.index)

    # If major is Unknown but CIP exists, use CIP code as the major name
    major = major.where(
        major != "Unknown",
        "CIP " + cip_clean
    )

    # If CIP is also Unknown, keep Unknown
    major = major.replace("CIP Unknown", "Unknown")

    return major

# ==================================================
# FIND CSV FILES
# ==================================================

csv_files = sorted(folder.glob("*.csv"))

if not csv_files:
    raise FileNotFoundError(f"No CSV files found inside folder: {folder}")

print(f"Found {len(csv_files)} CSV files.")

# ==================================================
# CHECK DISK SPACE
# ==================================================

total, used, free = shutil.disk_usage(".")

print(f"Free disk space: {free / (1024**3):.2f} GB")
print("Starting clean combine...\n")

# ==================================================
# FIRST PASS: COLLECT ALL ORIGINAL COLUMNS
# This prevents mismatched columns between different years
# ==================================================

all_original_columns = []

for csv_file in csv_files:
    try:
        temp_header = pd.read_csv(
            csv_file,
            nrows=0,
            low_memory=False,
            encoding_errors="replace"
        )

        for col in temp_header.columns:
            if col not in all_original_columns:
                all_original_columns.append(col)

    except Exception as e:
        print(f"Could not read header from {csv_file.name}: {e}")

clean_columns = [
    "clean_year",
    "clean_award_level_code",
    "clean_award_level_name",
    "clean_degree_group",
    "clean_cip_code",
    "clean_major_name",
    "clean_degree_count"
]

output_columns = all_original_columns + clean_columns

print(f"Original columns found: {len(all_original_columns)}")
print(f"Final output columns: {len(output_columns)}\n")

# ==================================================
# PROCESS FILES ONE AT A TIME
# ==================================================

start_time = time.time()
total_rows_written = 0
header_written = False

for file_index, csv_file in enumerate(csv_files, start=1):
    file_start = time.time()
    year = get_year_from_filename(csv_file.name)

    print(f"Processing {file_index}/{len(csv_files)}: {csv_file.name}")

    try:
        reader = pd.read_csv(
            csv_file,
            chunksize=CHUNK_SIZE,
            low_memory=False,
            encoding_errors="replace"
        )

        file_rows = 0

        for chunk in reader:
            # -------------------------------
            # Find important columns
            # -------------------------------

            award_col = find_column(chunk, [
                "AWLEVEL",
                "AWARDLEVEL",
                "AWDLEVEL",
                "AWARD_LEVEL"
            ])

            cip_col = find_column(chunk, [
                "CIPCODE",
                "CIP_CODE",
                "CIP"
            ])

            major_col = find_column(chunk, [
                "CIPTITLE",
                "CIP_TITLE",
                "MAJOR_NAME",
                "PROGRAM",
                "PROGRAM_TITLE",
                "TITLE"
            ])

            count_col = find_column(chunk, [
                "CTOTALT",
                "TOTAL",
                "COUNT",
                "DEGREE_COUNT",
                "AWARDS",
                "COMPLETIONS"
            ])

            # -------------------------------
            # Add clean columns
            # -------------------------------

            chunk["clean_year"] = year

            if award_col:
                chunk["clean_award_level_code"] = pd.to_numeric(
                    chunk[award_col],
                    errors="coerce"
                )
                chunk["clean_award_level_name"] = (
                    chunk["clean_award_level_code"]
                    .map(award_level_map)
                    .fillna("Unknown")
                )
                chunk["clean_degree_group"] = chunk["clean_award_level_code"].apply(degree_group)
            else:
                chunk["clean_award_level_code"] = pd.NA
                chunk["clean_award_level_name"] = "Unknown"
                chunk["clean_degree_group"] = "Unknown"

            if cip_col:
                chunk["clean_cip_code"] = chunk[cip_col].apply(clean_text)
            else:
                chunk["clean_cip_code"] = "Unknown"

            chunk["clean_major_name"] = make_major_name(chunk, major_col, cip_col)

            if count_col:
                chunk["clean_degree_count"] = pd.to_numeric(
                    chunk[count_col],
                    errors="coerce"
                ).fillna(0).astype("int64")
            else:
                chunk["clean_degree_count"] = 0

            # -------------------------------
            # Make sure clean columns have no NaN
            # -------------------------------

            chunk["clean_year"] = chunk["clean_year"].fillna("Unknown")
            chunk["clean_award_level_name"] = chunk["clean_award_level_name"].fillna("Unknown")
            chunk["clean_degree_group"] = chunk["clean_degree_group"].fillna("Unknown")
            chunk["clean_cip_code"] = chunk["clean_cip_code"].fillna("Unknown")
            chunk["clean_major_name"] = chunk["clean_major_name"].fillna("Unknown")
            chunk["clean_degree_count"] = chunk["clean_degree_count"].fillna(0)

            # -------------------------------
            # Match final output column order
            # Missing old-year columns become blank
            # -------------------------------

            chunk = chunk.reindex(columns=output_columns)

            # -------------------------------
            # Write directly to output
            # -------------------------------

            chunk.to_csv(
                output_file,
                mode="a",
                index=False,
                header=not header_written
            )

            header_written = True

            file_rows += len(chunk)
            total_rows_written += len(chunk)

            # Clean memory after each chunk
            del chunk
            gc.collect()

        file_time = time.time() - file_start
        elapsed = time.time() - start_time

        avg_time_per_file = elapsed / file_index
        remaining_files = len(csv_files) - file_index
        eta = avg_time_per_file * remaining_files

        total, used, free = shutil.disk_usage(".")

        print(f"  Saved rows from file: {file_rows:,}")
        print(f"  File time: {format_seconds(file_time)}")
        print(f"  Total rows so far: {total_rows_written:,}")
        print(f"  Total time: {format_seconds(elapsed)}")
        print(f"  Estimated time left: {format_seconds(eta)}")
        print(f"  Free disk space now: {free / (1024**3):.2f} GB\n")

    except Exception as e:
        print(f"  ERROR with file: {csv_file.name}")
        print(f"  Reason: {e}\n")
        continue

# ==================================================
# DONE
# ==================================================

total_time = time.time() - start_time

print("DONE")
print(f"Output file created: {output_file}")
print(f"Total rows written: {total_rows_written:,}")
print(f"Total time: {format_seconds(total_time)}")

gc.collect()

Found 41 CSV files.
Free disk space: 532.72 GB
Starting clean combine...

Original columns found: 233
Final output columns: 240

Processing 1/41: 1984_c1984_cip.csv
  Saved rows from file: 114,727
  File time: 5s
  Total rows so far: 114,727
  Total time: 5s
  Estimated time left: 3m 39s
  Free disk space now: 532.68 GB

Processing 2/41: 1985_c1985_cip.csv
  Saved rows from file: 116,605
  File time: 5s
  Total rows so far: 231,332
  Total time: 11s
  Estimated time left: 3m 35s
  Free disk space now: 532.64 GB

Processing 3/41: 1986_c1986_cip.csv
  Saved rows from file: 117,479
  File time: 5s
  Total rows so far: 348,811
  Total time: 16s
  Estimated time left: 3m 32s
  Free disk space now: 532.61 GB

Processing 4/41: 1987_c1987_cip.csv
  Saved rows from file: 126,442
  File time: 6s
  Total rows so far: 475,253
  Total time: 23s
  Estimated time left: 3m 33s
  Free disk space now: 532.58 GB

Processing 5/41: 1988_c1988_cip.csv
  Saved rows from file: 131,154
  File time: 6s
  Total rows so far: 606,407
  Total time: 29s
  Estimated time left: 3m 32s
  Free disk space now: 532.54 GB

Processing 6/41: 1989_c1989_cip.csv
  Saved rows from file: 132,972
  File time: 6s
  Total rows so far: 739,379
  Total time: 36s
  Estimated time left: 3m 31s
  Free disk space now: 532.50 GB

Processing 7/41: 1990_c8990cip.csv
  Saved rows from file: 129,518
  File time: 6s
  Total rows so far: 868,897
  Total time: 42s
  Estimated time left: 3m 27s
  Free disk space now: 532.47 GB

Processing 8/41: 1991_c1991_cip.csv
  Saved rows from file: 129,860
  File time: 6s
  Total rows so far: 998,757
  Total time: 49s
  Estimated time left: 3m 22s
  Free disk space now: 532.44 GB

Processing 9/41: 1992_c1992_cip.csv
  Saved rows from file: 134,877
  File time: 6s
  Total rows so far: 1,133,634
  Total time: 55s
  Estimated time left: 3m 18s
  Free disk space now: 532.39 GB

Processing 10/41: 1993_c1993_cip.csv
  Saved rows from file: 138,445
  File time: 6s
  Total rows so far: 1,272,079
  Total time: 1m 2s
  Estimated time left: 3m 14s
  Free disk space now: 532.36 GB

Processing 11/41: 1994_c1994_cip.csv
  Saved rows from file: 139,740
  File time: 6s
  Total rows so far: 1,411,819
  Total time: 1m 9s
  Estimated time left: 3m 10s
  Free disk space now: 532.31 GB

Processing 12/41: 1995_c9495_a.csv
  Saved rows from file: 163,377
  File time: 8s
  Total rows so far: 1,575,196
  Total time: 1m 17s
  Estimated time left: 3m 8s
  Free disk space now: 532.26 GB

Processing 13/41: 1996_c9596_a.csv
  Saved rows from file: 158,885
  File time: 7s
  Total rows so far: 1,734,081
  Total time: 1m 25s
  Estimated time left: 3m 3s
  Free disk space now: 532.22 GB

Processing 14/41: 1997_c9697_a.csv
  Saved rows from file: 159,007
  File time: 7s
  Total rows so far: 1,893,088
  Total time: 1m 32s
  Estimated time left: 2m 58s
  Free disk space now: 532.15 GB

Processing 15/41: 1998_c9798_a.csv
  Saved rows from file: 201,825
  File time: 9s
  Total rows so far: 2,094,913
  Total time: 1m 42s
  Estimated time left: 2m 56s
  Free disk space now: 532.09 GB

Processing 16/41: 1999_c9899_a.csv
  Saved rows from file: 153,166
  File time: 7s
  Total rows so far: 2,248,079
  Total time: 1m 49s
  Estimated time left: 2m 50s
  Free disk space now: 532.04 GB

Processing 17/41: 2000_c2000_a.csv
  Saved rows from file: 173,137
  File time: 8s
  Total rows so far: 2,421,216
  Total time: 1m 57s
  Estimated time left: 2m 45s
  Free disk space now: 532.00 GB

Processing 18/41: 2001_c2001_a.csv
  Saved rows from file: 194,569
  File time: 9s
  Total rows so far: 2,615,785
  Total time: 2m 6s
  Estimated time left: 2m 41s
  Free disk space now: 531.93 GB

Processing 19/41: 2002_c2002_a.csv
  Saved rows from file: 200,336
  File time: 9s
  Total rows so far: 2,816,121
  Total time: 2m 15s
  Estimated time left: 2m 37s
  Free disk space now: 531.87 GB

Processing 20/41: 2003_c2003_a.csv
  Saved rows from file: 211,859
  File time: 9s
  Total rows so far: 3,027,980
  Total time: 2m 25s
  Estimated time left: 2m 32s
  Free disk space now: 531.79 GB

Processing 21/41: 2004_c2004_a_rv.csv
  Saved rows from file: 219,809
  File time: 9s
  Total rows so far: 3,247,789
  Total time: 2m 35s
  Estimated time left: 2m 27s
  Free disk space now: 531.73 GB

Processing 22/41: 2005_c2005_a_rv.csv
  Saved rows from file: 230,217
  File time: 10s
  Total rows so far: 3,478,006
  Total time: 2m 45s
  Estimated time left: 2m 23s
  Free disk space now: 531.65 GB

Processing 23/41: 2006_c2006_a_rv.csv
  Saved rows from file: 238,450
  File time: 10s
  Total rows so far: 3,716,456
  Total time: 2m 56s
  Estimated time left: 2m 18s
  Free disk space now: 531.57 GB

Processing 24/41: 2007_c2007_a_rv.csv
  Saved rows from file: 240,422
  File time: 11s
  Total rows so far: 3,956,878
  Total time: 3m 8s
  Estimated time left: 2m 13s
  Free disk space now: 532.85 GB

Processing 25/41: 2008_c2008_a_rv.csv
  Saved rows from file: 247,127
  File time: 12s
  Total rows so far: 4,204,005
  Total time: 3m 20s
  Estimated time left: 2m 8s
  Free disk space now: 532.76 GB

Processing 26/41: 2009_c2009_a_rv.csv
  Saved rows from file: 255,934
  File time: 12s
  Total rows so far: 4,459,939
  Total time: 3m 32s
  Estimated time left: 2m 2s
  Free disk space now: 532.65 GB

Processing 27/41: 2010_c2010_a_rv.csv
  Saved rows from file: 265,728
  File time: 13s
  Total rows so far: 4,725,667
  Total time: 3m 46s
  Estimated time left: 1m 57s
  Free disk space now: 532.54 GB

Processing 28/41: 2011_c2011_a_rv.csv
  Saved rows from file: 265,825
  File time: 12s
  Total rows so far: 4,991,492
  Total time: 3m 58s
  Estimated time left: 1m 50s
  Free disk space now: 532.45 GB

Processing 29/41: 2012_c2012_a_rv.csv
  Saved rows from file: 270,217
  File time: 12s
  Total rows so far: 5,261,709
  Total time: 4m 11s
  Estimated time left: 1m 44s
  Free disk space now: 532.36 GB

Processing 30/41: 2013_c2013_a_rv.csv
  Saved rows from file: 284,937
  File time: 12s
  Total rows so far: 5,546,646
  Total time: 4m 24s
  Estimated time left: 1m 37s
  Free disk space now: 532.26 GB

Processing 31/41: 2014_c2014_a_rv.csv
  Saved rows from file: 293,274
  File time: 13s
  Total rows so far: 5,839,920
  Total time: 4m 38s
  Estimated time left: 1m 29s
  Free disk space now: 532.17 GB

Processing 32/41: 2015_c2015_a_rv.csv
  Saved rows from file: 300,263
  File time: 13s
  Total rows so far: 6,140,183
  Total time: 4m 51s
  Estimated time left: 1m 22s
  Free disk space now: 532.06 GB

Processing 33/41: 2016_c2016_a_rv.csv
  Saved rows from file: 302,043
  File time: 13s
  Total rows so far: 6,442,226
  Total time: 5m 5s
  Estimated time left: 1m 14s
  Free disk space now: 531.96 GB

Processing 34/41: 2017_c2017_a_rv.csv
  Saved rows from file: 308,882
  File time: 14s
  Total rows so far: 6,751,108
  Total time: 5m 19s
  Estimated time left: 1m 5s
  Free disk space now: 531.85 GB

Processing 35/41: 2018_c2018_a_rv.csv
  Saved rows from file: 290,149
  File time: 13s
  Total rows so far: 7,041,257
  Total time: 5m 33s
  Estimated time left: 57s
  Free disk space now: 531.76 GB

Processing 36/41: 2019_c2019_a_rv.csv
  Saved rows from file: 290,972
  File time: 13s
  Total rows so far: 7,332,229
  Total time: 5m 46s
  Estimated time left: 48s
  Free disk space now: 531.65 GB

Processing 37/41: 2020_c2020_a_rv.csv
  Saved rows from file: 289,833
  File time: 13s
  Total rows so far: 7,622,062
  Total time: 5m 59s
  Estimated time left: 38s
  Free disk space now: 531.56 GB

Processing 38/41: 2021_c2021_a_rv.csv
  Saved rows from file: 296,365
  File time: 13s
  Total rows so far: 7,918,427
  Total time: 6m 13s
  Estimated time left: 29s
  Free disk space now: 531.46 GB

Processing 39/41: 2022_c2022_a_rv.csv
  Saved rows from file: 301,055
  File time: 13s
  Total rows so far: 8,219,482
  Total time: 6m 26s
  Estimated time left: 19s
  Free disk space now: 531.35 GB

Processing 40/41: 2023_c2023_a_RV.csv
  Saved rows from file: 303,460
  File time: 13s
  Total rows so far: 8,522,942
  Total time: 6m 40s
  Estimated time left: 10s
  Free disk space now: 531.26 GB

Processing 41/41: 2024_c2024_a.csv
  Saved rows from file: 307,707
  File time: 14s
  Total rows so far: 8,830,649
  Total time: 6m 54s
  Estimated time left: 0s
  Free disk space now: 531.15 GB

DONE
Output file created: IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv
Total rows written: 8,830,649
Total time: 6m 54s

0

# do not use this due to overload memory problem
# print(df)
# print(final_dataset)
# df = pd.read_csv(file)

################################
# Use this instead:
# print(df.shape)
# print(df.head())
###################################
# data science project
# memory optimization 
# So yes, this is optimization, but it is memory optimization, not always speed optimization. It should prevent your computer from running out of space/memory.

In [19]:
import pandas as pd

preview = pd.read_csv(
    "IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv",
    nrows=20,
    low_memory=False,
    keep_default_na=False
)

print(preview[[
    "clean_year",
    "clean_cip_code",
    "clean_major_name",
    "clean_award_level_name",
    "clean_degree_group",
    "clean_degree_count"
]])

    clean_year  clean_cip_code clean_major_name clean_award_level_name  \
0         1984           10102        CIP 10102               Bachelor
1         1984           10102        CIP 10102                 Master
2         1984           10103        CIP 10103               Bachelor
3         1984           20201        CIP 20201               Bachelor
4         1984           20301        CIP 20301               Bachelor
5         1984           20399        CIP 20399                 Master
6         1984           20501        CIP 20501               Bachelor
7         1984           29999        CIP 29999               Bachelor
8         1984           29999        CIP 29999                 Master
9         1984           30499        CIP 30499               Bachelor
10        1984           40301        CIP 40301               Bachelor
11        1984           40301        CIP 40301                 Master
12        1984           60101        CIP 60101               Bachelor
13        1984           60201        CIP 60201               Bachelor
14        1984           60301        CIP 60301               Bachelor
15        1984           60401        CIP 60401               Bachelor
16        1984           60401        CIP 60401                 Master
17        1984           60501        CIP 60501               Bachelor
18        1984           60501        CIP 60501                 Master
19        1984           61401        CIP 61401               Bachelor

   clean_degree_group  clean_degree_count
0            Bachelor                   0
1              Master                   0
2            Bachelor                   0
3            Bachelor                   0
4            Bachelor                   0
5              Master                   0
6            Bachelor                   0
7            Bachelor                   0
8              Master                   0
9            Bachelor                   0
10           Bachelor                   0
11             Master                   0
12           Bachelor                   0
13           Bachelor                   0
14           Bachelor                   0
15           Bachelor                   0
16             Master                   0
17           Bachelor                   0
18             Master                   0
19           Bachelor                   0

In [24]:
import pandas as pd
import time
from pathlib import Path

file = Path("IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv")

if not file.exists():
    raise FileNotFoundError("Output file not found. Check the file name/location.")

missing_count = 0
total_rows = 0
chunk_number = 0

start_time = time.time()

for chunk in pd.read_csv(
    file,
    usecols=["clean_major_name"],   # only read this column, faster
    chunksize=100_000,
    low_memory=False,
    keep_default_na=False
):
    chunk_number += 1
    total_rows += len(chunk)

    s = chunk["clean_major_name"].astype(str).str.strip().str.lower()

    missing_count += (
        (s == "") |
        (s.isin(["nan", "none", "null"]))
    ).sum()

    elapsed = time.time() - start_time

    print(
        f"Checked chunk {chunk_number} | rows checked: {total_rows:,} | bad rows: {missing_count:,} | time: {elapsed:.1f}s",
        flush=True
    )

print("====================================")
print("DONE")
print("Total rows checked:", total_rows)
print("Bad clean_major_name rows:", missing_count)

Checked chunk 1 | rows checked: 100,000 | bad rows: 0 | time: 0.2s
Checked chunk 2 | rows checked: 200,000 | bad rows: 0 | time: 0.4s
Checked chunk 3 | rows checked: 300,000 | bad rows: 0 | time: 0.6s
Checked chunk 4 | rows checked: 400,000 | bad rows: 0 | time: 0.8s
Checked chunk 5 | rows checked: 500,000 | bad rows: 0 | time: 1.0s
Checked chunk 6 | rows checked: 600,000 | bad rows: 0 | time: 1.2s
Checked chunk 7 | rows checked: 700,000 | bad rows: 0 | time: 1.4s
Checked chunk 8 | rows checked: 800,000 | bad rows: 0 | time: 1.6s
Checked chunk 9 | rows checked: 900,000 | bad rows: 0 | time: 1.8s
Checked chunk 10 | rows checked: 1,000,000 | bad rows: 0 | time: 2.0s
Checked chunk 11 | rows checked: 1,100,000 | bad rows: 0 | time: 2.2s
Checked chunk 12 | rows checked: 1,200,000 | bad rows: 0 | time: 2.4s
Checked chunk 13 | rows checked: 1,300,000 | bad rows: 0 | time: 2.6s
Checked chunk 14 | rows checked: 1,400,000 | bad rows: 0 | time: 2.8s
Checked chunk 15 | rows checked: 1,500,000 | bad rows: 0 | time: 3.0s
Checked chunk 16 | rows checked: 1,600,000 | bad rows: 0 | time: 3.3s
Checked chunk 17 | rows checked: 1,700,000 | bad rows: 0 | time: 3.5s
Checked chunk 18 | rows checked: 1,800,000 | bad rows: 0 | time: 3.8s
Checked chunk 19 | rows checked: 1,900,000 | bad rows: 0 | time: 4.0s
Checked chunk 20 | rows checked: 2,000,000 | bad rows: 0 | time: 4.2s
Checked chunk 21 | rows checked: 2,100,000 | bad rows: 0 | time: 4.4s
Checked chunk 22 | rows checked: 2,200,000 | bad rows: 0 | time: 4.6s
Checked chunk 23 | rows checked: 2,300,000 | bad rows: 0 | time: 4.9s
Checked chunk 24 | rows checked: 2,400,000 | bad rows: 0 | time: 5.1s
Checked chunk 25 | rows checked: 2,500,000 | bad rows: 0 | time: 5.3s
Checked chunk 26 | rows checked: 2,600,000 | bad rows: 0 | time: 5.5s
Checked chunk 27 | rows checked: 2,700,000 | bad rows: 0 | time: 5.7s
Checked chunk 28 | rows checked: 2,800,000 | bad rows: 0 | time: 6.0s
Checked chunk 29 | rows checked: 2,900,000 | bad rows: 0 | time: 6.2s
Checked chunk 30 | rows checked: 3,000,000 | bad rows: 0 | time: 6.4s
Checked chunk 31 | rows checked: 3,100,000 | bad rows: 0 | time: 6.7s
Checked chunk 32 | rows checked: 3,200,000 | bad rows: 0 | time: 6.9s
Checked chunk 33 | rows checked: 3,300,000 | bad rows: 0 | time: 7.1s
Checked chunk 34 | rows checked: 3,400,000 | bad rows: 0 | time: 7.3s
Checked chunk 35 | rows checked: 3,500,000 | bad rows: 0 | time: 7.5s
Checked chunk 36 | rows checked: 3,600,000 | bad rows: 0 | time: 7.8s
Checked chunk 37 | rows checked: 3,700,000 | bad rows: 0 | time: 8.0s
Checked chunk 38 | rows checked: 3,800,000 | bad rows: 0 | time: 8.2s
Checked chunk 39 | rows checked: 3,900,000 | bad rows: 0 | time: 8.4s
Checked chunk 40 | rows checked: 4,000,000 | bad rows: 0 | time: 8.7s
Checked chunk 41 | rows checked: 4,100,000 | bad rows: 0 | time: 8.9s
Checked chunk 42 | rows checked: 4,200,000 | bad rows: 0 | time: 9.1s
Checked chunk 43 | rows checked: 4,300,000 | bad rows: 0 | time: 9.4s
Checked chunk 44 | rows checked: 4,400,000 | bad rows: 0 | time: 9.6s
Checked chunk 45 | rows checked: 4,500,000 | bad rows: 0 | time: 9.9s
Checked chunk 46 | rows checked: 4,600,000 | bad rows: 0 | time: 10.1s
Checked chunk 47 | rows checked: 4,700,000 | bad rows: 0 | time: 10.4s
Checked chunk 48 | rows checked: 4,800,000 | bad rows: 0 | time: 10.6s
Checked chunk 49 | rows checked: 4,900,000 | bad rows: 0 | time: 10.8s
Checked chunk 50 | rows checked: 5,000,000 | bad rows: 0 | time: 11.0s
Checked chunk 51 | rows checked: 5,100,000 | bad rows: 0 | time: 11.3s
Checked chunk 52 | rows checked: 5,200,000 | bad rows: 0 | time: 11.5s
Checked chunk 53 | rows checked: 5,300,000 | bad rows: 0 | time: 11.7s
Checked chunk 54 | rows checked: 5,400,000 | bad rows: 0 | time: 11.9s
Checked chunk 55 | rows checked: 5,500,000 | bad rows: 0 | time: 12.2s
Checked chunk 56 | rows checked: 5,600,000 | bad rows: 0 | time: 12.4s
Checked chunk 57 | rows checked: 5,700,000 | bad rows: 0 | time: 12.6s
Checked chunk 58 | rows checked: 5,800,000 | bad rows: 0 | time: 12.9s
Checked chunk 59 | rows checked: 5,900,000 | bad rows: 0 | time: 13.1s
Checked chunk 60 | rows checked: 6,000,000 | bad rows: 0 | time: 13.3s
Checked chunk 61 | rows checked: 6,100,000 | bad rows: 0 | time: 13.5s
Checked chunk 62 | rows checked: 6,200,000 | bad rows: 0 | time: 13.8s
Checked chunk 63 | rows checked: 6,300,000 | bad rows: 0 | time: 14.0s
Checked chunk 64 | rows checked: 6,400,000 | bad rows: 0 | time: 14.2s
Checked chunk 65 | rows checked: 6,500,000 | bad rows: 0 | time: 14.4s
Checked chunk 66 | rows checked: 6,600,000 | bad rows: 0 | time: 14.6s
Checked chunk 67 | rows checked: 6,700,000 | bad rows: 0 | time: 14.8s
Checked chunk 68 | rows checked: 6,800,000 | bad rows: 0 | time: 15.1s
Checked chunk 69 | rows checked: 6,900,000 | bad rows: 0 | time: 15.3s
Checked chunk 70 | rows checked: 7,000,000 | bad rows: 0 | time: 15.5s
Checked chunk 71 | rows checked: 7,100,000 | bad rows: 0 | time: 15.8s
Checked chunk 72 | rows checked: 7,200,000 | bad rows: 0 | time: 16.0s
Checked chunk 73 | rows checked: 7,300,000 | bad rows: 0 | time: 16.2s
Checked chunk 74 | rows checked: 7,400,000 | bad rows: 0 | time: 16.4s
Checked chunk 75 | rows checked: 7,500,000 | bad rows: 0 | time: 16.7s
Checked chunk 76 | rows checked: 7,600,000 | bad rows: 0 | time: 16.9s
Checked chunk 77 | rows checked: 7,700,000 | bad rows: 0 | time: 17.1s
Checked chunk 78 | rows checked: 7,800,000 | bad rows: 0 | time: 17.3s
Checked chunk 79 | rows checked: 7,900,000 | bad rows: 0 | time: 17.5s
Checked chunk 80 | rows checked: 8,000,000 | bad rows: 0 | time: 17.8s
Checked chunk 81 | rows checked: 8,100,000 | bad rows: 0 | time: 18.0s
Checked chunk 82 | rows checked: 8,200,000 | bad rows: 0 | time: 18.2s
Checked chunk 83 | rows checked: 8,300,000 | bad rows: 0 | time: 18.4s
Checked chunk 84 | rows checked: 8,400,000 | bad rows: 0 | time: 18.7s
Checked chunk 85 | rows checked: 8,500,000 | bad rows: 0 | time: 18.9s
Checked chunk 86 | rows checked: 8,600,000 | bad rows: 0 | time: 19.1s
Checked chunk 87 | rows checked: 8,700,000 | bad rows: 0 | time: 19.3s
Checked chunk 88 | rows checked: 8,800,000 | bad rows: 0 | time: 19.5s
Checked chunk 89 | rows checked: 8,830,649 | bad rows: 0 | time: 19.6s
====================================
DONE
Total rows checked: 8830649
Bad clean_major_name rows: 0

# REad all

In [27]:
import pandas as pd

file = "IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv"

preview = pd.read_csv(
    file,
    nrows=20,
    low_memory=False,
    keep_default_na=False
)

display(preview)

,unitid,cipcode,awlevel,crace15,crace16,part,crace01,crace02,crace03,crace04,...,DVCWHW,CNRALW,CDISTEDP,clean_year,clean_award_level_code,clean_award_level_name,clean_degree_group,clean_cip_code,clean_major_name,clean_degree_count
0,100654,10102,5,11,0,,,,,,...,,,,1984,5,Bachelor,Bachelor,10102,CIP 10102,0
1,100654,10102,7,14,0,,,,,,...,,,,1984,7,Master,Master,10102,CIP 10102,0
2,100654,10103,5,1,1,,,,,,...,,,,1984,5,Bachelor,Bachelor,10103,CIP 10103,0
3,100654,20201,5,3,0,,,,,,...,,,,1984,5,Bachelor,Bachelor,20201,CIP 20201,0
4,100654,20301,5,3,0,,,,,,...,,,,1984,5,Bachelor,Bachelor,20301,CIP 20301,0
5,100654,20399,7,11,3,,,,,,...,,,,1984,7,Master,Master,20399,CIP 20399,0
6,100654,20501,5,2,0,,,,,,...,,,,1984,5,Bachelor,Bachelor,20501,CIP 20501,0
7,100654,29999,5,1,0,,,,,,...,,,,1984,5,Bachelor,Bachelor,29999,CIP 29999,0
8,100654,29999,7,10,0,,,,,,...,,,,1984,7,Master,Master,29999,CIP 29999,0
9,100654,30499,5,2,0,,,,,,...,,,,1984,5,Bachelor,Bachelor,30499,CIP 30499,0
10,100654,40301,5,7,2,,,,,,...,,,,1984,5,Bachelor,Bachelor,40301,CIP 40301,0
11,100654,40301,7,10,0,,,,,,...,,,,1984,7,Master,Master,40301,CIP 40301,0
12,100654,60101,5,8,12,,,,,,...,,,,1984,5,Bachelor,Bachelor,60101,CIP 60101,0
13,100654,60201,5,17,14,,,,,,...,,,,1984,5,Bachelor,Bachelor,60201,CIP 60201,0
14,100654,60301,5,5,2,,,,,,...,,,,1984,5,Bachelor,Bachelor,60301,CIP 60301,0
15,100654,60401,5,17,22,,,,,,...,,,,1984,5,Bachelor,Bachelor,60401,CIP 60401,0
16,100654,60401,7,91,16,,,,,,...,,,,1984,7,Master,Master,60401,CIP 60401,0
17,100654,60501,5,14,3,,,,,,...,,,,1984,5,Bachelor,Bachelor,60501,CIP 60501,0
18,100654,60501,7,11,1,,,,,,...,,,,1984,7,Master,Master,60501,CIP 60501,0
19,100654,61401,5,22,12,,,,,,...,,,,1984,5,Bachelor,Bachelor,61401,CIP 61401,0

In [29]:
import pandas as pd

file = "IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv"

clean_cols = [
    "clean_year",
    "clean_cip_code",
    "clean_major_name",
    "clean_award_level_name",
    "clean_degree_group",
    "clean_degree_count"
]

preview = pd.read_csv(
    file,
    usecols=clean_cols,
    nrows=30,
    low_memory=False,
    keep_default_na=False
)

display(preview)

,clean_year,clean_award_level_name,clean_degree_group,clean_cip_code,clean_major_name,clean_degree_count
0,1984,Bachelor,Bachelor,10102,CIP 10102,0
1,1984,Master,Master,10102,CIP 10102,0
2,1984,Bachelor,Bachelor,10103,CIP 10103,0
3,1984,Bachelor,Bachelor,20201,CIP 20201,0
4,1984,Bachelor,Bachelor,20301,CIP 20301,0
5,1984,Master,Master,20399,CIP 20399,0
6,1984,Bachelor,Bachelor,20501,CIP 20501,0
7,1984,Bachelor,Bachelor,29999,CIP 29999,0
8,1984,Master,Master,29999,CIP 29999,0
9,1984,Bachelor,Bachelor,30499,CIP 30499,0
10,1984,Bachelor,Bachelor,40301,CIP 40301,0
11,1984,Master,Master,40301,CIP 40301,0
12,1984,Bachelor,Bachelor,60101,CIP 60101,0
13,1984,Bachelor,Bachelor,60201,CIP 60201,0
14,1984,Bachelor,Bachelor,60301,CIP 60301,0
15,1984,Bachelor,Bachelor,60401,CIP 60401,0
16,1984,Master,Master,60401,CIP 60401,0
17,1984,Bachelor,Bachelor,60501,CIP 60501,0
18,1984,Master,Master,60501,CIP 60501,0
19,1984,Bachelor,Bachelor,61401,CIP 61401,0
20,1984,Bachelor,Bachelor,70601,CIP 70601,0
21,1984,Bachelor,Bachelor,100104,CIP 100104,0
22,1984,Bachelor,Bachelor,110101,CIP 110101,0
23,1984,Master,Master,110101,CIP 110101,0
24,1984,Master,Master,130101,CIP 130101,0
25,1984,Bachelor,Bachelor,130499,CIP 130499,0
26,1984,Master,Master,130499,CIP 130499,0
27,1984,Master,Master,131004,CIP 131004,0
28,1984,Bachelor,Bachelor,131005,CIP 131005,0
29,1984,Master,Master,131005,CIP 131005,0

# Print only column names

In [31]:
import pandas as pd

file = "IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv"

columns = pd.read_csv(file, nrows=0).columns.tolist()

for col in columns:
    print(col)

unitid
cipcode
awlevel
crace15
crace16
part
crace01
crace02
crace03
crace04
crace05
crace06
crace07
crace08
crace09
crace10
crace11
crace12
crace13
crace14
bal_m
bal_w
imprac01
imprac02
imprac03
imprac04
imprac05
imprac06
imprac07
imprac08
imprac09
imprac10
imprac11
imprac12
imprac13
imprac14
imprac15
imprac16
ix01
ix02
ix03
ix04
ix05
ix06
ix07
ix08
ix09
ix10
ix11
ix12
ix13
ix14
ix15
ix16
cbalm
cbalw
xcrace01
xcrace02
xcrace03
xcrace04
xcrace05
xcrace06
xcrace07
xcrace08
xcrace09
xcrace10
xcrace11
xcrace12
xcrace13
xcrace14
xcrace15
xcrace16
xcrace17
crace17
xcrace18
crace18
xcrace19
crace19
xcrace20
crace20
xcrace21
crace21
xcrace22
crace22
xcrace23
crace23
xcrace24
crace24
majornum
UNITID
CIPCODE
AWLEVEL
MAJORNUM
XCRACE01
CRACE01
XCRACE02
CRACE02
XCRACE03
CRACE03
XCRACE04
CRACE04
XCRACE05
CRACE05
XCRACE06
CRACE06
XCRACE07
CRACE07
XCRACE08
CRACE08
XCRACE09
CRACE09
XCRACE10
CRACE10
XCRACE11
CRACE11
XCRACE12
CRACE12
XCRACE13
CRACE13
XCRACE14
CRACE14
XCRACE15
CRACE15
XCRACE16
CRACE16
XCRACE17
CRACE17
XCRACE18
CRACE18
XCRACE19
CRACE19
XCRACE20
CRACE20
XCRACE21
CRACE21
XCRACE22
CRACE22
XCRACE23
CRACE23
XCRACE24
CRACE24
XCNRALM
CNRALM
XCNRALW
CNRALW
XCUNKNM
CUNKNM
XCUNKNW
CUNKNW
XCTOTALM
CTOTALM
XCTOTALW
CTOTALW
XCNRALT
CNRALT
XCUNKNT
CUNKNT
XCTOTALT
CTOTALT
XCHISPM
CHISPM
XCHISPW
CHISPW
XCAIANM
CAIANM
XCAIANW
CAIANW
XCASIAM
CASIAM
XCASIAW
CASIAW
XCBKAAM
CBKAAM
XCBKAAW
CBKAAW
XCNHPIM
CNHPIM
XCNHPIW
CNHPIW
XCWHITM
CWHITM
XCWHITW
CWHITW
XC2MORM
C2MORM
XC2MORW
C2MORW
XCHISPT
CHISPT
XCAIANT
CAIANT
XCASIAT
CASIAT
XCBKAAT
CBKAAT
XCNHPIT
CNHPIT
XCWHITT
CWHITT
XC2MORT
C2MORT
XDVCAIT
DVCAIT
XDVCAIM
DVCAIM
XDVCAIW
DVCAIW
XDVCAPT
DVCAPT
XDVCAPM
DVCAPM
XDVCAPW
DVCAPW
XDVCBKT
DVCBKT
XDVCBKM
DVCBKM
XDVCBKW
DVCBKW
XDVCHST
DVCHST
XDVCHSM
DVCHSM
XDVCHSW
DVCHSW
XDVCWHT
DVCWHT
XDVCWHM
DVCWHM
XDVCWHW
DVCWHW
CNRALW
CDISTEDP
clean_year
clean_award_level_code
clean_award_level_name
clean_degree_group
clean_cip_code
clean_major_name
clean_degree_count

In [34]:
#4. View rows from a specific year only
import pandas as pd

file = "IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv"

clean_cols = [
    "clean_year",
    "clean_cip_code",
    "clean_major_name",
    "clean_award_level_name",
    "clean_degree_group",
    "clean_degree_count"
]

rows_to_show = []

for chunk in pd.read_csv(
    file,
    usecols=clean_cols,
    chunksize=100_000,
    low_memory=False,
    keep_default_na=False
):
    chunk["clean_year"] = pd.to_numeric(chunk["clean_year"], errors="coerce")

    part = chunk[chunk["clean_year"] == 2022]

    if not part.empty:
        rows_to_show.append(part.head(20))

    if rows_to_show:
        break

result = pd.concat(rows_to_show, ignore_index=True)

display(result)

,clean_year,clean_award_level_name,clean_degree_group,clean_cip_code,clean_major_name,clean_degree_count
0,2022,Bachelor,Bachelor,1.0999,CIP 1.0999,9
1,2022,Bachelor,Bachelor,1.1001,CIP 1.1001,7
2,2022,Master,Master,1.1001,CIP 1.1001,7
3,2022,Doctor - research/scholarship,Doctor,1.1001,CIP 1.1001,3
4,2022,Bachelor,Bachelor,1.9999,CIP 1.9999,1
5,2022,Master,Master,1.9999,CIP 1.9999,8
6,2022,Doctor - research/scholarship,Doctor,1.9999,CIP 1.9999,3
7,2022,Bachelor,Bachelor,3.0599,CIP 3.0599,8
8,2022,Bachelor,Bachelor,4.0301,CIP 4.0301,3
9,2022,Master,Master,4.0301,CIP 4.0301,12
10,2022,Master,Master,9.0199,CIP 9.0199,11
11,2022,Bachelor,Bachelor,10.0202,CIP 10.0202,17
12,2022,Bachelor,Bachelor,11.0101,CIP 11.0101,41
13,2022,Master,Master,11.0101,CIP 11.0101,16
14,2022,Post-master certificate,Certificate/Other,13.0101,CIP 13.0101,0
15,2022,Master,Master,13.0401,CIP 13.0401,1
16,2022,Bachelor,Bachelor,13.1001,CIP 13.1001,3
17,2022,Master,Master,13.1001,CIP 13.1001,1
18,2022,Bachelor,Bachelor,13.1012,CIP 13.1012,8
19,2022,Bachelor,Bachelor,13.1202,CIP 13.1202,6

In [38]:
# View Bachelor rows only
import pandas as pd

file = "IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv"

clean_cols = [
    "clean_year",
    "clean_cip_code",
    "clean_major_name",
    "clean_award_level_name",
    "clean_degree_group",
    "clean_degree_count"
]

rows_to_show = []

for chunk in pd.read_csv(
    file,
    usecols=clean_cols,
    chunksize=100_000,
    low_memory=False,
    keep_default_na=False
):
    part = chunk[chunk["clean_degree_group"] == "Bachelor"]

    if not part.empty:
        rows_to_show.append(part.head(30))

    if rows_to_show:
        break

result = pd.concat(rows_to_show, ignore_index=True)

display(result)

,clean_year,clean_award_level_name,clean_degree_group,clean_cip_code,clean_major_name,clean_degree_count
0,1984,Bachelor,Bachelor,10102,CIP 10102,0
1,1984,Bachelor,Bachelor,10103,CIP 10103,0
2,1984,Bachelor,Bachelor,20201,CIP 20201,0
3,1984,Bachelor,Bachelor,20301,CIP 20301,0
4,1984,Bachelor,Bachelor,20501,CIP 20501,0
5,1984,Bachelor,Bachelor,29999,CIP 29999,0
6,1984,Bachelor,Bachelor,30499,CIP 30499,0
7,1984,Bachelor,Bachelor,40301,CIP 40301,0
8,1984,Bachelor,Bachelor,60101,CIP 60101,0
9,1984,Bachelor,Bachelor,60201,CIP 60201,0
10,1984,Bachelor,Bachelor,60301,CIP 60301,0
11,1984,Bachelor,Bachelor,60401,CIP 60401,0
12,1984,Bachelor,Bachelor,60501,CIP 60501,0
13,1984,Bachelor,Bachelor,61401,CIP 61401,0
14,1984,Bachelor,Bachelor,70601,CIP 70601,0
15,1984,Bachelor,Bachelor,100104,CIP 100104,0
16,1984,Bachelor,Bachelor,110101,CIP 110101,0
17,1984,Bachelor,Bachelor,130499,CIP 130499,0
18,1984,Bachelor,Bachelor,131005,CIP 131005,0
19,1984,Bachelor,Bachelor,131006,CIP 131006,0
20,1984,Bachelor,Bachelor,131012,CIP 131012,0
21,1984,Bachelor,Bachelor,131201,CIP 131201,0
22,1984,Bachelor,Bachelor,131301,CIP 131301,0
23,1984,Bachelor,Bachelor,131302,CIP 131302,0
24,1984,Bachelor,Bachelor,131303,CIP 131303,0
25,1984,Bachelor,Bachelor,131305,CIP 131305,0
26,1984,Bachelor,Bachelor,131309,CIP 131309,0
27,1984,Bachelor,Bachelor,131312,CIP 131312,0
28,1984,Bachelor,Bachelor,131314,CIP 131314,0
29,1984,Bachelor,Bachelor,140801,CIP 140801,0

In [40]:
import pandas as pd

file = "IPEDS_ALL_ORIGINAL_INFO_CLEAN.csv"

clean_cols = [
    "clean_year",
    "clean_cip_code",
    "clean_major_name",
    "clean_award_level_name",
    "clean_degree_group",
    "clean_degree_count"
]

preview = pd.read_csv(
    file,
    usecols=clean_cols,
    nrows=50,
    low_memory=False,
    keep_default_na=False
)

display(preview)

,clean_year,clean_award_level_name,clean_degree_group,clean_cip_code,clean_major_name,clean_degree_count
0,1984,Bachelor,Bachelor,10102,CIP 10102,0
1,1984,Master,Master,10102,CIP 10102,0
2,1984,Bachelor,Bachelor,10103,CIP 10103,0
3,1984,Bachelor,Bachelor,20201,CIP 20201,0
4,1984,Bachelor,Bachelor,20301,CIP 20301,0
5,1984,Master,Master,20399,CIP 20399,0
6,1984,Bachelor,Bachelor,20501,CIP 20501,0
7,1984,Bachelor,Bachelor,29999,CIP 29999,0
8,1984,Master,Master,29999,CIP 29999,0
9,1984,Bachelor,Bachelor,30499,CIP 30499,0
10,1984,Bachelor,Bachelor,40301,CIP 40301,0
11,1984,Master,Master,40301,CIP 40301,0
12,1984,Bachelor,Bachelor,60101,CIP 60101,0
13,1984,Bachelor,Bachelor,60201,CIP 60201,0
14,1984,Bachelor,Bachelor,60301,CIP 60301,0
15,1984,Bachelor,Bachelor,60401,CIP 60401,0
16,1984,Master,Master,60401,CIP 60401,0
17,1984,Bachelor,Bachelor,60501,CIP 60501,0
18,1984,Master,Master,60501,CIP 60501,0
19,1984,Bachelor,Bachelor,61401,CIP 61401,0
20,1984,Bachelor,Bachelor,70601,CIP 70601,0
21,1984,Bachelor,Bachelor,100104,CIP 100104,0
22,1984,Bachelor,Bachelor,110101,CIP 110101,0
23,1984,Master,Master,110101,CIP 110101,0
24,1984,Master,Master,130101,CIP 130101,0
25,1984,Bachelor,Bachelor,130499,CIP 130499,0
26,1984,Master,Master,130499,CIP 130499,0
27,1984,Master,Master,131004,CIP 131004,0
28,1984,Bachelor,Bachelor,131005,CIP 131005,0
29,1984,Master,Master,131005,CIP 131005,0
30,1984,Bachelor,Bachelor,131006,CIP 131006,0
31,1984,Master,Master,131006,CIP 131006,0
32,1984,Bachelor,Bachelor,131012,CIP 131012,0
33,1984,Master,Master,131012,CIP 131012,0
34,1984,Master,Master,131099,CIP 131099,0
35,1984,Master,Master,131101,CIP 131101,0
36,1984,Bachelor,Bachelor,131201,CIP 131201,0
37,1984,Master,Master,131201,CIP 131201,0
38,1984,Bachelor,Bachelor,131301,CIP 131301,0
39,1984,Master,Master,131301,CIP 131301,0
40,1984,Bachelor,Bachelor,131302,CIP 131302,0
41,1984,Bachelor,Bachelor,131303,CIP 131303,0
42,1984,Master,Master,131303,CIP 131303,0
43,1984,Bachelor,Bachelor,131305,CIP 131305,0
44,1984,Master,Master,131305,CIP 131305,0
45,1984,Bachelor,Bachelor,131309,CIP 131309,0
46,1984,Master,Master,131311,CIP 131311,0
47,1984,Bachelor,Bachelor,131312,CIP 131312,0
48,1984,Bachelor,Bachelor,131314,CIP 131314,0
49,1984,Master,Master,139999,CIP 139999,0